### ISSUE TITLE
Invalid code is generated when two sinks in the same component (with valid unique names) consume the same topic

### ISSUE THREAD

**Issue by thzinc** [syncromatics/kafmesh#39]
Given a component called "positions" defining the following sinks:

```yaml
sinks:
  - name: Positions Sink
    description: Sinks vehicle positions into the warehouse
    message: warehouseService.vehicleId.position

  - name: VehicleStatus Sink
    description: Sinks the latest vehicle status to core
    message: warehouseService.vehicleId.position
```

The `discover.km.go` file will contain two functions named `discover_Positions_WarehouseServiceVehicleIDPosition_Sink`. The function should be uniquely named based on the defined sinks' names.
